### ISSUE TITLE
Publish Message with JWT

### ISSUE THREAD

**Issue by sh0umik** [centrifugal/centrifuge-dart#23]
I can successfully connect to Centrifugo server using JWT and setToken() method. Tested with admin panel and i can only receive message.

Whenever i try to send message i get this `Unhandled Exception: Error{code: 103, message: permission denied}`

Here is what i am trying 
```
 void sendMessage(SendChatMessage message) async {
    final output = jsonEncode({'token': profileInfo.chatToken, 'data' : {'msg': message.message}});
    final data = utf8.encode(output);
    await _subscriptions[message.channel].publish(data);
  }
```

**Comment by sh0umik** [comment]
Setting the publish = true in server config solved the problem. Thanks for quick response in gitter chat.

More about this, are described here.

https://centrifugal.github.io/centrifugo/faq/#can-i-publish-new-messages-over-websocket-connection-from-client

**Comment by autocorrectoff** [comment]
the link is dead. anyplace else where one could find how to do this?

**Comment by FZambia** [comment]
@autocorrectoff https://centrifugal.dev/docs/faq#can-i-publish-new-messages-over-a-websocket-connection-from-a-client

**Comment by autocorrectoff** [comment]
@FZambia it says:

> It's possible to publish messages into channels directly from a client (when publish channel option is enabled).

It should actually be **allow_publish_for_subscriber** ?

Because if I just add publish: true to config I get:

> centrifugo    | {"level":"warn","key":"publish","namespace_name":"test","time":"2024-05-07T07:54:24Z","message":"unknown key found in the namespace object"}

**Comment by FZambia** [comment]
> It should actually be allow_publish_for_subscriber ?

Yep. Some option names changed since 2019, use https://centrifugal.dev/docs/server/channels#channel-options as a source of truth.
