### ISSUE TITLE
Use relative imports everywhere

### ISSUE THREAD

**Issue by synw** [centrifugal/centrifuge-dart#25]
My ide gets confused about the types sometimes when I read this library's code. I think this is because there are some mixed relative and absolute imports for internal files: sometimes it is relative and in some other places library files are imported with package:

I suggest that we move all internal imports to relative to avoid namespace confusions and have a better coding experience

**Comment by FZambia** [comment]
@mogol hello, German, what do you think?

**Comment by mogol** [comment]
Hey,
I tend to use relative imports in the library, absolute was "auto" generated by ide, so it can be replaced without issues.

**Comment by synw** [comment]
I'm not familiar with auto generated code, got it. Thanks for the explanation. It feels strange to see for example in `client.dart` the `transport.dart` being imported twice: one as absolute and one as relative. But well that's the way it is
