### ISSUE TITLE
Raise protobuf package version 0.13.2 to 1.0.1

### ISSUE THREAD

**Issue by Holofox** [centrifugal/centrifuge-dart#29]
Hello! Sorry, is it possible to upgrade the protobuf package to the latest?

> Because centrifuge >=0.2.0 depends on protobuf ^0.13.2 and my_flutter_app depends on protobuf ^1.0.1, centrifuge >=0.2.0 is forbidden.
So, because my_flutter_app depends on centrifuge ^0.4.1, version solving failed.
pub upgrade failed (1; So, because my_flutter_app depends on centrifuge ^0.4.1, version solving failed.)

Thank you in advance for considering the matter.

**Comment by FZambia** [comment]
@Holofox hello, yeah this definitely makes a lot of sense - me or @mogol will take a look soon, if you have a possibility to rebuild generated code with latest protoc for Dart and update dependency to library - feel free to send pr.
