### ISSUE TITLE
Unable to send RPC request

### ISSUE THREAD

**Issue by Holofox** [centrifugal/centrifuge-dart#33]
Hello again!  I noticed that RPC requests are not sent. The problem occurs when deserializing and serializing data. Shouldn't we use the type [Uint8List](https://api.flutter.dev/flutter/dart-typed_data/Uint8List-class.html) instead of ``List<int>``?

To clarify the situation, now the centrifuge client on Dart allows you to send RPC requests in binary form (``List<int>``).

Before bringing to this form, I convert the bodies of an RPC request through the [.writeToBuffer()](https://github.com/dart-lang/protobuf/blob/cf7e6792835d08a4ed637754290e3c54a37ab68f/protobuf/lib/src/protobuf/generated_message.dart#L158) or 

```dart
utf8.encode(jsonEncode(request.toProto3Json());
```

method, it is worth noting that the binary result of these operations is different;

What should I do to correctly send a request? A little later I will try to supplement the information about the problem I am facing.

**Comment by FZambia** [comment]
@Holofox hello, I don't have quick answer since I am not a Dart developer in general, will try to reproduce this as soon as I can.

@mogol do you have time to look at this question?

**Comment by FZambia** [comment]
@Holofox added sending RPC to console example, see https://github.com/centrifugal/centrifuge-dart/blob/master/example/console/simple.dart#L68
