### ISSUE TITLE
Message recovery

### ISSUE THREAD

**Issue by rexfordnyrk** [centrifugal/centrifuge-dart#43]
please i'd like to know if message recovery mechanism functionality is working with this client. and if not what would it take to get that working?

**Comment by FZambia** [comment]
@rexfordnyrk  hello, see https://github.com/centrifugal/centrifuge-dart#feature-matrix - recovery not supported yet. In general to add support for it we need to [sth like this](https://github.com/centrifugal/centrifuge-swift/pull/39) but here.

**Comment by FZambia** [comment]
Supported in https://github.com/centrifugal/centrifuge-dart/releases/tag/v0.9.0
