### ISSUE TITLE
protobuf version

### ISSUE THREAD

**Issue by doev03** [centrifugal/centrifuge-dart#45]
please update the protobuf version

**Comment by FZambia** [comment]
@doev03 hello, did you come across any problem with current one?

**Comment by doev03** [comment]
@FZambia I get conflicts with other packages

**Comment by FZambia** [comment]
What kind of conflict? Which version you expect here?

**Comment by HamdiTayara** [comment]
Same problem here.. my project depends on protobuf ^2.0.0, I'm getting packages conflicts (centrifuge depends on protobuf ^1.0.1)

**Comment by FZambia** [comment]
@HamdiTayara hello, should be solved by https://github.com/centrifugal/centrifuge-dart/pull/48

**Comment by FZambia** [comment]
v0.6.0 with null safety migration and protobuf version update released
