### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifuge-dart#47]
This issue will track progress of migration.

**Comment by FZambia** [comment]
Dependencies migrated to null safe versions in 6965d6d28ae1f7fe8b23a50a538f888e7420e1d5

**Comment by FZambia** [comment]
Updated dev dependencies in 555d30fa2a0ad595a6c2612dd61a299310a577bc

```
dart pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

All your dependencies declare support for null-safety.
```

**Comment by FZambia** [comment]
An ongoing pr with library code migration: #48

**Comment by srdjan86** [comment]
Hello,

Sorry for rushing you, but do you maybe know if there is any date by which we can expect the library to be upgraded to null safety?

Cheers

**Comment by FZambia** [comment]
@srdjan86 hello, could you help to test out code in #48 ?

**Comment by srdjan86** [comment]
Hey @FZambia,

I have been using code from #48 for 2 weeks not in the app that I am developing. I have found no issues.

**Comment by FZambia** [comment]
@srdjan86 thanks, really appreciate help with this!

@mogol wanted to take a final look, if he doesn't find a time till this weekend we will merge that pr in the current form.

**Comment by FZambia** [comment]
v0.6.0 released
