### ISSUE TITLE
Bug. Null check operator used on a null value. When centrifugal client close

### ISSUE THREAD

**Issue by r-oman-G** [centrifugal/centrifuge-dart#58]
return _socket!.close();
<img width="1330" alt="IntelliJ IDEA 12 09 15-49-29" src="https://user-images.githubusercontent.com/38914451/145399493-7c7a6fef-f079-46d6-a295-01d6a29707d3.png">

https://github.com/centrifugal/centrifuge-dart/blame/53dc5a90a97831faafa5bd60f2c8f3237f6a1b6f/lib/src/transport.dart#L84

```
#0      Transport.close (package:centrifuge/src/transport.dart:84:19)
#1      ClientImpl.disconnect (package:centrifuge/src/client.dart:207:22)
#2      _CentrifugeConnectMixin.close (package:magistral/src/features/socket_connector/data/centrifuge_connector.dart:167:13)
<asynchronous suspension>
```

**Comment by FZambia** [comment]
Hello, @r-oman-G ! This is [already fixed](https://github.com/centrifugal/centrifuge-dart/blob/v0.8.0/lib/src/transport.dart#L117) as of 0.8.0 I suppose.
