### ISSUE TITLE
Supporting Centrifugo v3

### ISSUE THREAD

**Issue by robert-virkus** [centrifugal/centrifuge-dart#74]
Hi, what would be required in principle to support v3 of the protocol? I would assume and hope that "only" the proto needs to be exchanged and the commands would need to be re-generated, is that roughly right?
Could the client in principle detect the server side version and decide during runtime which command encoder/decoder to use?

**Comment by robert-virkus** [comment]
I happen to have the requirement to support both web and other platforms with v3 (at least for now) and I would like to stick to the "official" plugin for  maintenance reasons. Did I understand you correctly, it is your policy that client SDKs should never support older server versions?

**Comment by FZambia** [comment]
Yeah - it's a decision made to move Centrifugo project forward. Unfortunately supporting both protocol versions adds too much complexity for maintenance which is simply unaffordable for Centrifugo at this stage.
