### ISSUE TITLE
ClientDisconnectedError

### ISSUE THREAD

**Issue by furkanKotic** [centrifugal/centrifuge-dart#76]
While the application was in the foreground, the following error occurred in the log records. It wasn't in the background.

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: ClientDisconnectedError
       at Transport.sendAsyncMessage(transport.dart:155)
       at ClientImpl._onPing(client.dart:711)
       at ClientImpl._onPush(client.dart:719)
       at Transport._onData.<fn>.<fn>(transport.dart:266)
       at _GrowableList.forEach(_GrowableList.java)
       at Transport._onData.<fn>(transport.dart:262)
```

![image](https://user-images.githubusercontent.com/92918781/221579882-4e15dcf9-02ca-4d4c-b502-5c23a7f5a9d9.png)

**Comment by FZambia** [comment]
Hello, it seems that this error is thrown when client tries to send pong to closed connection. Does the connection stops working (not reconnecting) after that?

**Comment by furkanKotic** [comment]
No. It works because I can still get messages even though the error occurs.

**Comment by FZambia** [comment]
I see, in general it's normal that connection errors happen. And if SDK successfully reconnected - then it's an expected thing. Probably we should handle and suppress this error in the SDK when sending pong 🤔

**Comment by furkanKotic** [comment]
It seems to be ok as the message transmission is not interrupted but it is a bit sad to see this in Firebase. I will be happy if improvement is made. thanks

**Comment by BrianMwas** [comment]
I am also getting the error. Though I get the following information:- Client Connecting

**Comment by TomBeckett** [comment]
Its something we see very often in our [Sentry](https://sentry.io/) logging. A bit frustrating as these errors take up a lot of our Sentry allowance (50k per month) and as can as I can see we're using the Dart SDK correctly 😕

**Comment by FZambia** [comment]
Trying to address this in #79

**Comment by FZambia** [comment]
Please let me know whether [v0.9.4](https://github.com/centrifugal/centrifuge-dart/releases/tag/v0.9.4) fixes this.

**Comment by TomBeckett** [comment]
@FZambia We've pulled this into our app and are pushing to production soon. Will let you know if we see an improvement. We've not forgotten about it 😃

**Comment by furkanKotic** [comment]
Significantly reduced log records. We can say the problem is solved.
Thanks 😃

**Comment by FZambia** [comment]
@TomBeckett hello, still waiting for the feedback about your use case, do you have any updates?
