### ISSUE TITLE
How can I get clientInfo from The LeaveEvent and JoinEvent etc, Because I want get the ClientInfo.connInfo and chanInfo.

### ISSUE THREAD

**Issue by hetao29** [centrifugal/centrifuge-dart#83]
Hi, I wan get the connInfo and chanInfo from the LeaveEvent and JoinEvent etc, But I cannot simply get it, Help me. 
THANKS.

**Comment by FZambia** [comment]
Hello, looks like these two are missing at this moment - need to add. Will try to do it very soon, if you decide to send PR before that - please let me know here.

**Comment by hetao29** [comment]
thanks @FZambia very much, my application upgrade the version from v2 to v5, It used by flutter app, weichat miniprogram(it use the raw websocket ,and the doc here https://developers.weixin.qq.com/miniprogram/dev/api/network/websocket/wx.connectSocket.html) and web app.

**Comment by FZambia** [comment]
Released with https://github.com/centrifugal/centrifuge-dart/releases/tag/v0.14.0, thanks @hetao29
