### ISSUE TITLE
A few more examples

### ISSUE THREAD

**Issue by ghost** [centrifugal/centrifuge-dart#9]
At the moment the demo works :)
I got it working after a few hours. Great stuff and well abstracted.

But i think that we should add an example that is little more data driven so its easier to play around with  Centrifuge.

Use this as a basis.
https://github.com/magicwave/mws_mqtt_client
which currently uses: https://github.com/shamblett/mqtt_client
Its for MQTT but is a good example.

It shows the server connected, and allows you to connect.
![Screenshot 2019-04-08 at 09 43 38](https://user-images.githubusercontent.com/20677314/55707179-474a2300-59e3-11e9-85f2-fdc94667584d.png)

It allows you to make new channels / topics, so you can play around.
![Screenshot 2019-04-08 at 09 43 53](https://user-images.githubusercontent.com/20677314/55707185-4c0ed700-59e3-11e9-8c81-3dece66b43b7.png)

It allows you to test putting data into those channels and see it coming back.

![Screenshot 2019-04-08 at 09 44 22](https://user-images.githubusercontent.com/20677314/55707199-503af480-59e3-11e9-8cd4-2ceecf3eb184.png)

Maybe add login - it does not have it yet.

----

Then it would be good to add a few examples to really show off how powerful centrifuge can be !

Maybe we should host here ?

I can start on the following below:

1.  A Classic Chat app example.

https://github.com/amsokol/flutter-grpc-tutorial
- At the moment it uses GRPC and so i just have to replace that with the centrifuge-dart calls.

2.  A real time document collaboration.

https://github.com/memspace/zefyr

![zefyr-1](https://user-images.githubusercontent.com/20677314/55707341-ab6ce700-59e3-11e9-8537-38a37350fea8.png)
- It has a real time update mechanism based on Quill Delta and so we can tap into that. There is golang code so we can add that to the golang examples to work in tandem with the Dart code.
- Will add many user cursors later. Just like you see in Google docs.

3. A Cal App is a good example also
- So peoples cals stay in sync on their many devices.

**Comment by FZambia** [comment]
@gedw99 I suppose everyone will be happy if you add one or more well crafted examples.

**Comment by FZambia** [comment]
fixed by @synw via #32
